- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: true
        upgrade: safe
        autoremove: true
        autoclean: true
      changed_when: false

  tasks:
    - import_tasks: tasks/repositories.yml
    - import_tasks: tasks/packages.yml
