- name: Keep packages up to date # noqa package-latest
  apt:
    autoclean: true
    autoremove: true
    install_recommends: false
    state: latest
    name:
      - htop
      - npm
      - tilix
      - tmux
      - tree
      - xclip
